# Generated by Django 4.0.6 on 2022-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
